agenda = [[],
[{ 'dia': 1, 'semana': 'Sexta-Feira', 'evento': 'Culto', 'hora': '19:20h', 'local': 'Templo Batista em Arvores Verdes' }],
[{ 'dia': 2, 'semana': 'Sexta-Feira', 'evento': 'Culto', 'hora': '19:20h', 'local': 'Templo Batista em Arvores Verdes' }],
[{ 'dia': 3, 'semana': 'Sexta-Feira', 'evento': 'Culto', 'hora': '19:20h', 'local': 'Templo Batista em Arvores Verdes' }],
[{ 'dia': 4, 'semana': 'Sexta-Feira', 'evento': 'Culto', 'hora': '19:20h', 'local': 'Templo Batista em Arvores Verdes' }],
[{ 'dia': 5, 'semana': 'Sexta-Feira', 'evento': 'Culto', 'hora': '19:20h', 'local': 'Templo Batista em Arvores Verdes' }],
[{ 'dia': 6, 'semana': 'Sexta-Feira', 'evento': 'Culto', 'hora': '19:20h', 'local': 'Templo Batista em Arvores Verdes' }],
[{ 'dia': 7, 'semana': 'Sexta-Feira', 'evento': 'Culto', 'hora': '19:20h', 'local': 'Templo Batista em Arvores Verdes' }],
[{ 'dia': 8, 'semana': 'Sexta-Feira', 'evento': 'Culto', 'hora': '19:20h', 'local': 'Templo Batista em Arvores Verdes' }],
[{ 'dia': 9, 'semana': 'Sexta-Feira', 'evento': 'Culto', 'hora': '19:20h', 'local': 'Templo Batista em Arvores Verdes' }],
[{ 'dia': 10, 'semana': 'Sexta-Feira', 'evento': 'Culto', 'hora': '19:20h', 'local': 'Templo Batista em Arvores Verdes' }],
[{ 'dia': 11, 'semana': 'Sexta-Feira', 'evento': 'Culto', 'hora': '19:20h', 'local': 'Templo Batista em Arvores Verdes' }],
[{ 'dia': 12, 'semana': 'Sexta-Feira', 'evento': 'Culto', 'hora': '19:20h', 'local': 'Templo Batista em Arvores Verdes' }],
[{ 'dia': 13, 'semana': 'Sexta-Feira', 'evento': 'Culto', 'hora': '19:20h', 'local': 'Templo Batista em Arvores Verdes' }],
[{ 'dia': 14, 'semana': 'Sexta-Feira', 'evento': 'Culto', 'hora': '19:20h', 'local': 'Templo Batista em Arvores Verdes' }],
[{ 'dia': 15, 'semana': 'Sexta-Feira', 'evento': 'Culto', 'hora': '19:20h', 'local': 'Templo Batista em Arvores Verdes' }],
[{ 'dia': 16, 'semana': 'Sexta-Feira', 'evento': 'Culto', 'hora': '19:20h', 'local': 'Templo Batista em Arvores Verdes' }],
[{ 'dia': 17, 'semana': 'Sexta-Feira', 'evento': 'Culto', 'hora': '19:20h', 'local': 'Templo Batista em Arvores Verdes' }],
[{ 'dia': 18, 'semana': 'Sexta-Feira', 'evento': 'Culto', 'hora': '19:20h', 'local': 'Templo Batista em Arvores Verdes' }],
[{ 'dia': 19, 'semana': 'Sexta-Feira', 'evento': 'Culto', 'hora': '19:20h', 'local': 'Templo Batista em Arvores Verdes' }],
[{ 'dia': 20, 'semana': 'Sexta-Feira', 'evento': 'Culto', 'hora': '19:20h', 'local': 'Templo Batista em Arvores Verdes' }],
[{ 'dia': 21, 'semana': 'Sexta-Feira', 'evento': 'Culto', 'hora': '19:20h', 'local': 'Templo Batista em Arvores Verdes' }],
[],
[],
[{ 'dia': 24, 'semana': 'Sabado', 'evento': 'Culto dia das Crianças', 'hora': '12:20h', 'local': 'Templo Batista em Arvores Verdes' }],
[{ 'dia': 25, 'semana': 'Domingo', 'evento': 'Culto', 'hora': '19:20h', 'local': 'Templo Batista em Arvores Verdes' }],
[{ 'dia': 26, 'semana': 'Sexta-Feira', 'evento': 'Culto', 'hora': '19:20h', 'local': 'Templo Batista em Arvores Verdes' }],
[{ 'dia': 27, 'semana': 'Sexta-Feira', 'evento': 'Culto', 'hora': '19:20h', 'local': 'Templo Batista em Arvores Verdes' }],
[{ 'dia': 28, 'semana': 'Sexta-Feira', 'evento': 'Culto', 'hora': '19:20h', 'local': 'Templo Batista em Arvores Verdes' }],
[{ 'dia': 29, 'semana': 'Sexta-Feira', 'evento': 'Culto', 'hora': '19:20h', 'local': 'Templo Batista em Arvores Verdes' }],
[{ 'dia': 30, 'semana': 'Sexta-Feira', 'evento': 'Culto', 'hora': '19:20h', 'local': 'Templo Batista em Arvores Verdes' }],
[{ 'dia': 31, 'semana': 'Sexta-Feira', 'evento': 'Culto', 'hora': '19:20h', 'local': 'Templo Batista em Arvores Verdes' }]
]
